### ISSUE TITLE
Question about location of view on screen.

### ISSUE THREAD

**Issue by adeldolgov** [LittleMango/StackLayoutManager#10]
Hello, how can when i locate my items without addiction margins and paddings? I want that the first card will be in start of my activity. Or how i can set margins for the first item?

**Comment by adeldolgov** [comment]
![image](https://user-images.githubusercontent.com/17458811/75664200-220d7580-5c83-11ea-8bb6-373b3b2c956d.png)
Something like this :

**Comment by LittleMango** [comment]
Since this requirement was not considered before, you can only copy the code of defaultlayout.kt and then modify  [this line](https://github.com/LittleMango/StackLayoutManager/blob/334e6d26bde127f39c7fc506bc639d3bf3bab76e/StackLayoutManager/src/main/java/com/littlemango/stacklayoutmanager/DefaultLayout.kt#L94). I'll change these methods to inheritable in the future.

**Comment by adeldolgov** [comment]
@LittleMango 
I need to download library then connect it to my Android Studio project and then rewrite this class? 
Or can I override class without manual downloading library?

**Comment by LittleMango** [comment]
@adeldolgov Just copy DefaultAnimation.kt, change the code mentioned above, then use this constructor to create layoutManager instance:
```
StackLayoutManager stackLayoutManager = new StackLayoutManager(ScrollOrientation.RIGHT_TO_LEFT, 5, DefaultAnimation.class, YoutCopyDefaultLayout.class);
```

**Comment by adeldolgov** [comment]
@LittleMango Awesome! Thank you :)
